### ISSUE TITLE
Cannot integrate using Carthage because the Xcode project lacks shared schemes for frameworks

### ISSUE THREAD

**Issue by samsonjs** [vimeo/VimeoNetworking#220]
The Xcode project doesn't have a shared schemes for frameworks so it cannot currently be used with Carthage.

[Carthage](https://github.com/Carthage/Carthage) is a dependency manager that can manage git submodules for you, and builds frameworks so you don't have to build your unchanging dependencies over and over as you develop. It would be cool to use it for VimeoNetworking too.

**Comment by jasonhawkins** [comment]
Hey @samsonjs thanks for your interest in VimeoNetworking and for trying to make it easier to integrate into more kinds of projects. We kicked around the idea of adding Carthage support, and even [created a branch](https://github.com/vimeo/VimeoNetworking/tree/tech/add-carthage-support) for it at one point, but ended up deciding that it wasn't something we could support long-term. Your issue here spawned some great discussions about dependency management over the past few months though, so thanks for that 😃 

For now, installing via CocoaPods (or as a submodule if you really want to get crazy) is the best way we offer for integrating VimeoNetworking into a project.

**Comment by dulgan** [comment]
So please just remove the few lines telling to use Carthage on the main readme.

**Comment by rpassis** [comment]
Hi @dulgan we have just merged a change to support Carthage integration. You will need to point the Cartfile to the develop branch until we cut a new release. Please let me know if that doesn’t work for you. 

Rog

**Comment by rpassis** [comment]
Hi @dulgan we have just merged a change to support Carthage integration. You will need to point the Cartfile to the develop branch until we cut a new release. Please let me know if that doesn’t work for you. 

Rog

**Comment by dulgan** [comment]
Hi, didn't jasonhawkins said that it wouldn't be supported ?
Sorry if I misleaded.
I'll try it tomorrow.

**Comment by jasonhawkins** [comment]
@dulgan Like @rpassis said, Carthage support was _juuust_ added 🎉 

Definitely feel free to open a new issue if you run into any trouble though.
