### ISSUE TITLE
Update dependency AFNetworking to 4.0

### ISSUE THREAD

**Issue by vishnugupta20** [vimeo/VimeoNetworking#418]
Hello,

I am getting Apple rejection of using depreciated UIWebView. AFNetworking was using UIWebView they have a fix released with version 4.0. When I am updating the my pod I getting below error.

> VimeoNetworking (from `Vimeo`) was resolved to 3.3.1, which depends on AFNetworking (= 3.1.0)

**Comment by BCtopics** [comment]
+1 having the same issue

**Comment by BCtopics** [comment]
I had this same issue. The dependency Is completely removed in the newest release. I'd suggest trying to update to the new version :)

**Comment by rpassis** [comment]
Thanks @BCtopics and glad to hear you've been able to update to the latest version.

@vishnugupta20 please let us know if you need any help. The version you need to update to is `4.1.0` so in your `Podfile`

```
pod 'VimeoNetworking', '4.1.0'
```

Then run

```
pod update VimeoNetworking`
```

Depending on which version of the library you are currently running there may be some (potentially minor) breaking changes. You can see the release notes [here](https://github.com/vimeo/VimeoNetworking/releases/tag/4.1.0)

Rog

**Comment by igoriols** [comment]
Hi @rpassis , may I use `VimeoNetworking` with `AFNetworking`?

**Comment by rpassis** [comment]
Hi @igoriols you don’t need to add any third party dependencies to use our library. 

FWIW (currently) we still implicitly depend on AFNetworking but this is internal to the library and an implementation detail that may change at any time.

**Comment by igoriols** [comment]
Hi @rpassis , I'm working on a project that already has the `AFNetworking` dependency, but I would like to include `VimeoNetworking`. 

I'm facing the following error: 'AFURLSessionManager.h' file not found in `UIRefreshControl+AFNetworking.h` of `VimeoNetworking`.

Here a sample project: 
https://github.com/igoriols/TestVimeoNetworkingWithAFNetworking

I think it is because there are files with the same name, so Xcode can't find the correct ones to import.

Can you help me solve this problem, please?

**Comment by rpassis** [comment]
Because we implicitly depend on AFNetworking, when you add the library as an external dependency it is pulling a different version (most likely with breaking API changes).

The easiest way to solve this is to lock the AFNetworking version in your podfile to `3.1.0`:

```
pod 'VimeoNetworking', '4.1.0'
pod 'AFNetworking', '3.1.0'
```

I've tried it with your sample project and was able to build it successfully.

The problem with this approach is that it means you are consuming a version of AFNetworking that includes `UIWebView` extensions, so if you are planning on submitting this to the AppStore you are going to have problems.

Alternatively, you will need to fork `VimeoNetworking` and make the required changes so that it can work with the latest version of AFNetworking. 

I hope it helps!
Rog

**Comment by igoriols** [comment]
Hi @rpassis, it didn't work... I ended up discarding `VimeoNetworking` and using the web API to make the requests using `URLSession`. In the future we are planning to remove `AFNetworking` from our app, but since they both are using different versions of `AFNetworking` even if there are files of the library inside `VimeoNetworking`, the compiler accuses that there is more than one version as source and the wich one will be used is undefined.

Thanks

**Comment by rpassis** [comment]
Thanks for the update @igoriols. We have an updated version of the networking library that no longer relies on AFNetworking as well. There are no current plans to release it publicly yet but keep an eye out for it over the next few months. In the meantime I think the move to just use a URLSession instead is pretty reasonable, specially if your use case is simple.
